// this file is automatically generated by git.version.ts script
<<<<<<< HEAD
export const versions = {version: '0.0.0', revision: 'ff747ef', branch: 'Allysa_Dev'};
=======
export const versions = {version: '0.0.0', revision: '3d0ae4f', branch: 'master'};
>>>>>>> 12c1400204af75c2f94df7c6e6c9739e9c71c275
