// this file is automatically generated by git.version.ts script
<<<<<<< HEAD
export const versions = {version: '0.0.0', revision: 'eb75874', branch: 'master'};
=======
export const versions = {version: '0.0.0', revision: '4b5f0f7', branch: 'master'};
>>>>>>> 784edf8d4e92854b2adad74a2d35bd621a804a0f
