// this file is automatically generated by git.version.ts script
<<<<<<< HEAD
export const versions = {version: '0.0.0', revision: '5737482', branch: 'Tarjeet_Dev'};
=======
export const versions = {version: '0.0.0', revision: 'd0e8901', branch: 'master'};
>>>>>>> master
